// Code generated by internal/protocolcontract/cmd/generate; DO NOT EDIT.
// Source: contracts/mimi-protocol/contract.json

import Foundation

enum MimiProtocolContract {
    static let schemaVersion = 1
    static let protocolName = "mimi-agent-api"
    static let currentRevision = 2
    static let minimumSupportedClientRevision = 1
    static let minimumSupportedServerRevision = 1
    static let legacyClientRevision = 1
    static let legacyServerRevision = 1
    static let clientRevisionHeader = "X-Mimi-Protocol-Revision"
    static let minimumServerRevisionHeader = "X-Mimi-Minimum-Server-Protocol-Revision"
    static let serverRevisionHeader = "X-Mimi-Server-Protocol-Revision"
    static let minimumClientRevisionHeader = "X-Mimi-Minimum-Client-Protocol-Revision"
    static let specSHA256 = "2158fc83f85e51ab71e7841b167782bef42592131076470db6b8df10b6ff5716"
    static let declaredCapabilities: Set<String> = [
        "file_upload_v1",
    ]

    /// REST 与 WebSocket 共用同一组握手 header，旧 agentd 会安全忽略未知 header。
    static func applyClientHeaders(to request: inout URLRequest) {
        request.setValue(String(currentRevision), forHTTPHeaderField: clientRevisionHeader)
        request.setValue(String(minimumSupportedServerRevision), forHTTPHeaderField: minimumServerRevisionHeader)
    }
}
